# Generated by Django 4.2.1 on 2023-06-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sale_evaporator_sale_liquid_sale_pod_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaporator',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='liquid',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='single',
            name='sale',
        ),
        migrations.AlterField(
            model_name='evaporator',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evaporatorbrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podbrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='single',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.singlebrand', verbose_name='Бренд'),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
