# Generated by Django 4.2.1 on 2023-06-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_alter_evaporator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['liquid', 'pod', 'single', 'evaporator']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
