# Generated by Django 4.2.1 on 2023-06-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0006_alter_sale_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата продажи'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_for',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Продано за'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['liquid', 'pod', 'single', 'evaporator']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID проданного предмета'),
        ),
    ]
