# Generated by Django 4.2.1 on 2023-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sale_options_sale_date_sale_sold_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_of_sold',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Кол-во продано'),
        ),
    ]
