# Generated by Django 4.2.1 on 2023-06-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_evaporator_updated_evaporatorbrand_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaporator',
            options={'ordering': ['-updated'], 'verbose_name': 'Испарик', 'verbose_name_plural': 'Испарики'},
        ),
        migrations.AlterModelOptions(
            name='evaporatorbrand',
            options={'ordering': ['-updated'], 'verbose_name': 'Бред испариков', 'verbose_name_plural': 'Бренды испариков'},
        ),
        migrations.AlterModelOptions(
            name='liquid',
            options={'ordering': ['-updated'], 'verbose_name': 'Жидкость', 'verbose_name_plural': 'Жидкости'},
        ),
        migrations.AlterModelOptions(
            name='liquidbrand',
            options={'ordering': ['-updated'], 'verbose_name': 'Бренд Жидкостей', 'verbose_name_plural': 'Бренды Жидкостей'},
        ),
        migrations.AlterModelOptions(
            name='pod',
            options={'ordering': ['-updated'], 'verbose_name': 'Под', 'verbose_name_plural': 'Поды'},
        ),
        migrations.AlterModelOptions(
            name='podbrand',
            options={'ordering': ['-updated'], 'verbose_name': 'Бренд Подов', 'verbose_name_plural': 'Бренды Подов'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-updated'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='single',
            options={'ordering': ['-updated'], 'verbose_name': 'Одноразка', 'verbose_name_plural': 'Одноразки'},
        ),
        migrations.AlterModelOptions(
            name='singlebrand',
            options={'ordering': ['-updated'], 'verbose_name': 'Бренд одноразок', 'verbose_name_plural': 'Бренды одноразок'},
        ),
    ]
