# Generated by Django 4.2.1 on 2023-06-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sale_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=' Создано'),
        ),
    ]
