# Generated by Django 4.2.1 on 2023-06-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sale_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name=' Создано'),
        ),
    ]
