# Generated by Django 4.2.1 on 2023-06-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_sale_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount_of_sold',
        ),
    ]
